export const cars = [
  {
    id: 1,
    name: "Ford Fiesta",
    type: "Economy Car",
    image: "./assets/img/card1.png",
    seats: 5,
    transmission: "Automatic",
    age: "21+ Years",
    fuel: "1-lit / 2.5 km",
    category: "Compact",
  },
  {
    id: 2,
    name: "Nissan Versa",
    type: "Compact Car",
    image: "./assets/img/card2.png",
    seats: 5,
    transmission: "Automatic",
    age: "21+ Years",
    fuel: "1-lit / 2.5 km",
    category: "Compact",
  },
  {
    id: 3,
    name: "Toyota Corolla",
    type: "Mid-size Car",
    image: "./assets/img/card3.png",
    seats: 5,
    transmission: "Automatic",
    age: "21+ Years",
    fuel: "1-lit / 2.5 km",
    category: "Compact",
  },
  {
    id: 4,
    name: "Nissan Rogue",
    type: "Mid-size SUV",
    image: "./assets/img/card4.png",
    seats: 5,
    transmission: "Automatic",
    age: "21+ Years",
    fuel: "1-lit / 2.5 km",
    category: "Vans",
  },
  {
    id: 5,
    name: "Chevy Traverse",
    type: "Full-size SUV",
    image: "./assets/img/card5.png",
    seats: 5,
    transmission: "Automatic",
    age: "21+ Years",
    fuel: "1-lit / 2.5 km",
    category: "Vans",
  },
  {
    id: 6,
    name: "Nissan Altima",
    type: "Full-size Car",
    image: "./assets/img/card6.png",
    seats: 5,
    transmission: "Automatic",
    age: "21+ Years",
    fuel: "1-lit / 2.5 km",
    category: "Sports",
  },
];
